### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidbjames** [khanlou/NonEmptyArray#2]
Hi Soroush,

Would you add a permissive license to the source file? Preferably MIT?

Thanks,
David.

**Comment by khanlou** [comment]
This isn't enough? https://github.com/khanlou/NonEmptyArray/blob/master/LICENSE 

I'd rather not include the license in every file unless there's a really good reason to

**Comment by davidbjames** [comment]
That works. 👍 

(Agreed, licenses at the head of files is not pretty.)
